### PR TITLE
Add warning to contributing.md

### PR DESCRIPTION
**Pull request by maxmeyer**
Sorry. I made the change directly via website.

### CODE REVIEW

**Comment by maxmeyer** [comment]
Should we wrote an "announcement" to the gitter channel and the forums?

**Comment by tdreyno** [comment]
Thanks! I'm a little snowed under getting the release organized to manage the community very well right now.

**Comment by maxmeyer** [comment]
Done with https://gitter.im/middleman/middleman?at=5643c386aff38af50a9d482d in Gitter. I've got no account in the forums.

**Comment by maxmeyer** [comment]
Ok. I'm done for today. It's quarter to midnight here in Germany. Time for bed. Bye.

**Pull request merged**
