### PR TITLE
clear lazy map after resolving Tilt templates

### PR DESCRIPTION
**Pull request by mojavelinux**
- clear lazy map after resolving Tilt templates
- use raw ext to resolve Tilt template

### CODE REVIEW

**Comment by mojavelinux** [comment]
Since this method resolves the Tilt template for each extension, there's no reason to keep entries in the lazy map. If entries are left in the lazy map, this can later lead to the extensions_for method returning duplicate entries.

I also simplified the call to resolve the template using `mapping[ext]` instead of `::Tilt[".#{ext}"]` since these two calls do exactly the same thing.

**Comment by mojavelinux** [comment]
This may not be necessary if Tilt accepts the change upstream. See https://github.com/rtomayko/tilt/pull/324.

One way or another, we need agreement on this.

**Comment by tdreyno** [comment]
@mojavelinux Are we still waiting on that upstream patch for this?

**Comment by mojavelinux** [comment]
Still outstanding. See https://github.com/rtomayko/tilt/pull/324

Do you need me to rebase this?

**Comment by tdreyno** [comment]
Nope, I'll merge this fix for now

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
