### PR TITLE
Bump aruba

### PR DESCRIPTION
**Pull request by Arcovion**
Seeing if 0.8.1 works re: https://github.com/middleman/middleman/issues/1561#issuecomment-121627220

### CODE REVIEW

**Comment by maxmeyer** [comment]
Somehow `capybara` comes into scene, when the new matchers of `aruba` are used. Strange...

**Comment by maxmeyer** [comment]
```
[1] pry(#<Object>)> expect(files).to all be_an_existing_file
ArgumentError: rack-test requires a rack application, but none was given
from /home/user/.gem/ruby/2.2.2/gems/capybara-2.4.4/lib/capybara/rack_test/driver.rb:16:in `initialize'
```

**Comment by maxmeyer** [comment]
If you comment out the following line in `lib/middleman-core/step_definitions/server_steps.rb`:

``` ruby
# require 'capybara/cucumber'
```

And then run

```
bundle exec cucumber features/i18n_builder.feature:147
```

it works fine.

**Comment by maxmeyer** [comment]
@jnicklas Any idea? Have you ever seen such a behaviour?

**Comment by maxmeyer** [comment]
Got it.  `capybara` uses a method `rspec` also uses: `all` - see [RSpec's documentation](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/all-matcher) for more on this matcher.

```ruby
  if negated
    expect(files).not_to include an_existing_file
  else
    expect(files).to all be_an_existing_file
  end
```
Looking at the source of `~/.gem/ruby/2.2.2/gems/capybara-2.4.4/lib/capybara/dsl.rb` there seem to be some lines of code relevant here:

```ruby
def page
  Capybara.current_session
end

Session::DSL_METHODS.each do |method|
  define_method method do |*args, &block|
    page.send method, *args, &block
  end
end
```

At `~/.gem/ruby/2.2.2/gems/capybara-2.4.4/lib/capybara/session.rb:24` you will find this:

```ruby
    NODE_METHODS = [
      :all #[...]
    ]
```

I'm not sure how we best handle this. Will create an issue over at capybara.

**Comment by maxmeyer** [comment]
Opened an issue over at `capybara`. @tdreyno Ping.

**Comment by maxmeyer** [comment]
This seems to be a known issue. I ask the guys at `rspec` for some help.

**Comment by tdreyno** [comment]
So, this is not ready to merge, right?

**Comment by Arcovion** [comment]
Right, and might not be so simple as just updating the gem version...

**Pull request closed without merging**
