### PR TITLE
Move IRB initialization into a dedicated method.

### PR DESCRIPTION
**Pull request by AndrewKvalheim**
This change would allow for a [cleaner][clean] implementation of the [middleman-pry][middleman-pry] extension.

  [clean]: https://github.com/AndrewKvalheim/middleman-pry/commit/ba5b73a6666e4c1492c9470d762c2254f710e41a
  [middleman-pry]: https://github.com/AndrewKvalheim/middleman-pry

### CODE REVIEW

**Comment by AndrewKvalheim** [comment]
Would a [PR for v4][compare] be useful or do you merge from v3-stable into master?


  [compare]: https://github.com/middleman/middleman/compare/master...AndrewKvalheim:overridable-console-v4

**Comment by tdreyno** [comment]
I merge from v3 into master.

**Comment by alem0lars** [comment]
Is this already merged into master?

**Comment by AndrewKvalheim** [comment]
You can check at e.g.:
https://github.com/middleman/middleman/compare/master...v3-stable

**Pull request merged**
