### PR TITLE
Support dark mode color scheme

### PR DESCRIPTION
**Pull request by imme-emosol**
Dark is a less intrusive brightness
which makes it a more sensible default.

Make files more XHTML compatible
Remove sitemap.js
Add .css indent_size to .editorconfig
Remove unused css-selectors from colors.css
Move colors to separate file
Create colors.css
Wrap colors in @media(prefers-color-scheme: light)
Add colors.css to meta_pages' config.html.erb
Add colors.css to meta_pages' sitemap.html.erb
Add colors.css to meta_pages' index.html.erb
Add colors from sitemap.css to colors.css
Add colors from config.css to colors.css
Remove colors from sitemap.css
Remove colors from config.css

### CODE REVIEW

**Comment by tdreyno** [comment]
Looks good. Can you show screenshots of the new styles?

**Comment by imme-emosol** [comment]
Colors could probably use some attention.
Currently contrast is (too) low, according to https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast even though I can read everything perfectly. And the currently used set of glyphicons does not look as well as it does on a light background.

Anyway, screenshots:
image
image
image

**Comment by tdreyno** [comment]
@imme-emosol I use dark mode for everything and support this, however, I do think the color scheme is too low contrast and awkward looking. If someone could tweak the colors (borrowing from a VS Code theme maybe?), I'll merge

**Comment by imme-emosol** [comment]
image

**Comment by tdreyno** [comment]
Thanks!

**Comment by imme-emosol** [comment]
The changes compared to the previous commit:
* changed the background & font color to have bigger contrast, reusing middleman's yellow as a base for font color, background color was somewhat arbitrary,
* used an invert filter on the (glyph-) icons in the css,
* tweaked the font a bit for the dark scheme, because the meta.css etc. change the font in a way that on a dark background makes it to close together,

Hopefully it is enough of an improvement to merge it.

**Pull request merged**
