### PR TITLE
Remove trailing whitespace from layout template

### PR DESCRIPTION
**Pull request by vassilevsky**
Thanks to whoever made it red in Janus

### CODE REVIEW

**Comment by henrik** [comment]
:+1: Was about to make the same pullreq.

**Comment by vassilevsky** [comment]
Gonna reopen when I fix tests & give the branch a nicer name.

**Comment by vassilevsky** [comment]
Wow. Templates have been moved and extended; new templates don't have any hanging whitespace. No pull request needed anymore!

**Comment by tdreyno** [comment]
@vassilevsky Thanks for the help. We're hoping to get v4 out the door soon so everyone can enjoy the new templates. That said, we'll be supporting v3 for a long time, so maybe a PR is a good idea still.

**Comment by vassilevsky** [comment]
I think I'll let @henrik do it then :)

**Pull request closed without merging**
