### PR TITLE
Pull request for issue #1396 supporting srcset property in image tags

### PR DESCRIPTION
**Pull request by dperrymorrow**
this adds an extension for ```image_tag``` which enables used of ```srcset``` property in image tags, and having the urls for the paths built using asset_url just like it does for your main src. Leaves absolute
urls alone, _(having // in the path)_

**Erb:**
``` erb
<%= image_tage 'pic_1980.jpg', srcset: 'pic_640.jpg 2x, pic_1024.jpg 3x' %>
```
``` html
<!-- output -->
<img src="/images/pic_1980.jpg" srcset="/images/pic_640.jpg 2x, /images/pic_1024.jpg 3x">
```

Also work for markdown rendering, as it is processed through the ```image_tag``` helper.

**Markdown:***
``` markdown
![image](blank.gif){:srcset="image_2x.jpg 2x"}
```
``` html
<!-- output -->
<img src="/images/blank.gif" srcset="/images/image_2x.jpg 2x">
```

### CODE REVIEW

**Comment by tdreyno** [comment]
This is great. I actually don't see any reason not to put this directly in `image_tag` and skip the extension portion. What do you think?

**Comment by dperrymorrow** [comment]
Ok sure, so I should just extend image_tag in the default helpers instead of doing the whole 
``` ruby
class Middleman::Extensions::ImageSrcsetPaths < ::Middleman::Extension
```
bit? If so I fix that up.

**Comment by tdreyno** [comment]
Exactly. Thanks

**Comment by dperrymorrow** [comment]
ok, did that and squashed.

**Comment by tdreyno** [comment]
Lovely, thanks!

**Pull request merged**
