### PR TITLE
Include :locales and :data in live-reloadable types

### PR DESCRIPTION
**Pull request by johnnyshields**
Fixes https://github.com/middleman/middleman/issues/1698

I investigated the fix here and it turns out `middleman-core` is not sending anything to the callback in `middleman-livereload`.

In a nutshell:
* `on_change` needs to consider `:locales` and `:data` (in addition to `:sources`)
* `ignored?` needs to allow `:locales` and `:data` (in addition to `:sources`)

This allows the callbacks to go to `middleman-livereload`, and everything seems to work normally after that.

### CODE REVIEW

**Comment by tdreyno** [comment]
This is really smart. Let me take a little time this week to review.

**Comment by tdreyno** [comment]
Broke a ton of tests: https://travis-ci.org/middleman/middleman/jobs/95174834

**Comment by tdreyno** [comment]
Try running `TEST=true bundle exec rake test`

**Comment by tdreyno** [comment]
Not sure if the `TEST=true` is necessary. I don't think it is, but might explain why the Contracts tests didn't get run locally

**Comment by tdreyno** [comment]
Would love to get this in this week before the 4.0 final. Anything holding up fixing these test failures?

**Comment by johnnyshields** [comment]
@tdreyno unfortunately I'm a bit swamped at the moment and don't have time to look at the tests this week.

**Comment by tdreyno** [comment]
Going to merge this manually. Thanks @johnnyshields

**Pull request closed without merging**
