### PR TITLE
Add sourceMap comment to asset_hash and hash .map files by default

### PR DESCRIPTION
**Pull request by adam-h**
Test included expected usage :)

### CODE REVIEW

**Comment by adam-h** [comment]
Sourcemap syntax starts with a `#` these days, which this patch looks for. See https://developers.google.com/web/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed?hl=en

**Comment by adam-h** [comment]
Thanks @tdreyno! Any chance of getting a release pushed sometime soon?

**Comment by tdreyno** [comment]
Done. v4.1.2

**Comment by adam-h** [comment]
:bow: thank you!

**Pull request merged**
