### PR TITLE
resolves #1656 don't mangle URL inside tag

### LINKED ISSUE #1656: asset_host is mangling linked text that looks like a URL
The asset_host extension (as of Middleman 4.0.0.rc1) is mangling linked text that looks like a URL. Here's an example:

```
<a href="https://github.com/angular/angular.js">Angular.js</a>
```

Assuming the host is configured as `http://assets1.example.com`, here's the result we get:

```
<a href="https://github.com/angular/angular.js"http://assets1.example.com/>Angular.js</a>
```

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by mojavelinux** [comment]
I'm not sure if this is the best way to exclude this type of match. Frankly, the way URLs is currently being detected is very dangerous in my mind, so we're just whacking moles here. I'd much prefer to move to a much more strict set of known match locations and perhaps require the regex to be configured externally.

**Comment by tdreyno** [comment]
Can you rebase please?

**Comment by mojavelinux** [comment]
Certainly! Stay tuned.

**Comment by mojavelinux** [comment]
Rebase completed @tdreyno.

**Pull request merged**
