### PR TITLE
Add support for Ruby 2.4.0

### PR DESCRIPTION
**Pull request by danielbayerlein**
**Fix** ...
* ... `Gemfile` offenses
* ... `zero?` offenses
* ... syntax error
* ... `liquid` build error

**Add** ...
* ... support for Ruby 2.4.0

🎄 🎅 🤶 🎁

### CODE REVIEW

**Comment by danielbayerlein** [comment]
@tdreyno Do you have an idea why with Ruby 2.4.0 this error occurs?

```
     Failure/Error: require 'coffee_script'
     
     TypeError:
       wrong argument type Class (expected Module)
     # ./lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
     # ./lib/middleman-core/core_extensions/rendering.rb:11:in `block in <top (required)>'
     # ./lib/middleman-core/extensions.rb:91:in `load'
     # ./lib/middleman-core/extensions.rb:127:in `block in load_settings'
     # ./lib/middleman-core/extensions.rb:125:in `each'
     # ./lib/middleman-core/extensions.rb:125:in `load_settings'
     # ./lib/middleman-core/extension_manager.rb:12:in `initialize'
     # ./lib/middleman-core/application.rb:263:in `new'
     # ./lib/middleman-core/application.rb:263:in `initialize'
     # ./spec/middleman-core/util_spec.rb:167:in `new'
     # ./spec/middleman-core/util_spec.rb:167:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # LoadError:
     #   cannot load such file -- coffee_script
     #   ./lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
```

**Comment by danielbayerlein** [comment]
https://github.com/rails/ruby-coffee-script/issues/14

**Comment by tdreyno** [comment]
@danielbayerlein Thanks for looking into this. These Christmas Ruby releases always seem to have a rough dot zero. Hoping `2.4.1` will come quickly.

**Comment by ignisf** [comment]
Ping, https://github.com/cowboyd/therubyracer/issues/430 is closed now

**Comment by danielbayerlein** [comment]
**Update:**

* Ruby 2.2.6
  * `cucumber features/liquid.feature:3 # Scenario: Rendering liquid`
* Ruby 2.3.3
  * `cucumber features/liquid.feature:3 # Scenario: Rendering liquid`
* Ruby 2.4.0
  * `cucumber features/cache_buster.feature:10 # Scenario: Rendering html with the feature disabled`
  * `cucumber features/liquid.feature:3 # Scenario: Rendering liquid`

**Comment by danielbayerlein** [comment]
#2038 fix issues with Ruby 2.4.0

**Pull request closed without merging**
