### PR TITLE
Fix #2039 - ignore of I18n files

### LINKED ISSUE #2039: Middleman builds all localized files
I have a multilingual middleman site and each one is deployed on a separate domain. So my I18n extension is setup like this: `activate :i18n, :langs => [ TARGETTED_LOCALE ]`

Even if only one locale is specified, it will build and deploy all localized files, for example:
/localizable/privacy.de.html
/localizable/privacy.es.html
...

I also use a filter for the blog to only build the relevant blog articles this way:
```
activate :blog do |blog|
  blog.filter = proc { |article|
    article.tags.include? target.to_s
  }
end
```
Although the filter is working well, it also looks like it's building all blog articles, not just the filtered ones.

### PR DESCRIPTION
**Pull request by johnnyshields**
Fixes #2039

### CODE REVIEW

**Comment by tai-flywire** [comment]
Sorry to be a newb but what is the process for getting this into a release?  It seems like it was in all the development versions of 4.3.0 but didn't make the cut for the final release and every point release since then.  Has it just been forgotten?  It would be really useful for us to have this.

**Comment by tdreyno** [comment]
4.3 became 5.0 which isn't out yet. I can backport stable releases.

**Comment by tdreyno** [comment]
Published as `v4.3.4`

**Comment by tai-flywire** [comment]
Fantastic, thank you!!

**Pull request merged**
