### PR TITLE
Add test to `$ middleman init` using tmeplate

### PR DESCRIPTION
**Pull request by yterajima**
* using Middleman directory
* using github
    * user/repository
    * user/repository#branch
* using full path
    * contains "://"
    * contains "git@"

### CODE REVIEW

**Comment by yterajima** [comment]
I can't understand why only Travis-ci test is failed. In local machine(Mac), all test have passed.

**Comment by yterajima** [comment]
I'll try to investigate a little more.

**Comment by yterajima** [comment]
I understand. `git@github.com:~` needs permission. But travis-ci has not this permssion. So `$ middleman init MY_PROJECT -T git@github.com:middleman/middleman-templates-default.git` is failed.

I remove this test.

**Comment by tdreyno** [comment]
Wonderful. Thanks @yterajima 

It looks like it's still failing in `1.9.3`. I'm investigating.

**Comment by yterajima** [comment]
Thanks to investigating and reply.

And I was investigated, but did not know well. Maybe encoding trouble in ruby 1.9.3.

**Comment by yterajima** [comment]
If I changed server, this code worked.
https://gist.github.com/yterajima/795e7384c094c725ca87

API and 1.9.3 does not seem to go well .

**Comment by Arcovion** [comment]
[As of today](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) 1.9.3 is EOL. I vote for dropping 1.9.3 in v4, I know Padrino was thinking of doing so too.

**Comment by tdreyno** [comment]
@Arcovion Agreed. Updating Travis to match.

**Comment by Arcovion** [comment]
Awesome :tada:

**Pull request merged**
