### PR TITLE
Fix parent returns nil if path name changed.

### PR DESCRIPTION
**Pull request by balthisar**
Given that parent uses path (source path) for looking for file,
:38 @store.find_resource_by_destination_path() fails if the destination
path has changed. Using find_resource_by_path() ensures that we return
a parent resource.

### CODE REVIEW

**Comment by tdreyno** [comment]
Can you add a test case for the currently failing condition?

**Comment by balthisar** [comment]
> Can you add a test case for the currently failing condition?

Yup. Good chance to finally learn how testing works in Ruby. But this is the damndest thing: the bug this PR fixes is actually dependent on _how_ I set the resource's `destination_path`. If I simply:

~~~ ruby
resource.destination_path = new_output_path
~~~

…then this bug is exhibited; `parent` returns `nil` meaning `siblings` returns `nil`.

On the other hand, if I:

~~~ ruby
resource.destination_path.sub!(/something/, 'something_else')
~~~

Then all is well!

**Comment by balthisar** [comment]
@tdreyno, I've added #1874 based on Master with a failing test case. I've actually appended this to the existing `sitemap_traversal.feature` since it seems that the failure is simply an extension of that case.

It doesn't fail when run under this PR, of course.

**Comment by balthisar** [comment]
Right now `parent` uses the source `path` internally for all of its checks, except in :38 where we `find_resource_by_destination_path` (which fails in the expanded test case introduced in #1874).

This PR as it is works in all of the existing test cases, plus the new one that's introduced.

(from #1874):
> Seems like we should be unifying on destination_path, rather than source

This makes sense logically, except it requires rewriting `parent` completely to handle `directory_indexes` being used. Essentially we'd have to check for `directory_indexes` and disassemble the `destination_path`, leaving us back with pretty much the current state: the `path`.

- The PR in its current state leaves `parent` as a black box - internal implementation is private anyway.
- Passes `more-sitemap_traversal.feature`
- Passes the special case added to `sitemap_traversal.feature`
- Continues to use the original, source `path`.

**Comment by tdreyno** [comment]
Why does directory indexes introduce a problem? The renamed path will be present in `destination_path` with the appended `/index.html`.

Do we need additional logic to say "the parent of index.html is the next level up index.html"? I would think that would already be happening.

**Comment by balthisar** [comment]
> Do we need additional logic to say "the parent of index.html is the next level up index.html"? I would think that would already be happening.

Nope, you were right. I'd missed a destination_path earlier; all of the magic logic is already in place. This passes `sitemap_traversal.feature` (including the additional checks I added) and `more-sitemap_traversal.feature` which uses the directory_indexes.

**Comment by tdreyno** [comment]
Right, but this test is wrong:

```
    When I go to "/rename_paths/item_three/sibling_one.html"
    Then I should see "Parent: rename_paths/30_item_three/index.html"
```

`30_item_three/index.html` is not a sibling of `item_three/sibling_one.html`

**Comment by tdreyno** [comment]
The goal of this feature is to replicate something like the Apache file/directory browser

**Comment by balthisar** [comment]
Indeed. I'll fix that. I'm about to go on a holiday, but I'll leave the PR open. If you get tired of it sticking around, feel free to close it, and I'll deal with a fix when I get back.

**Comment by tdreyno** [comment]
no rush. Thanks @balthisar

**Pull request closed without merging**
