### PR TITLE
Test against Ruby 2.3.0 on Travis CI

### PR DESCRIPTION
**Pull request by tricknotes**

### CODE REVIEW

**Comment by tricknotes** [comment]
The test for Ruby 2.3.0 failed :broken_heart:  https://travis-ci.org/middleman/middleman/jobs/98787681

**Comment by tdreyno** [comment]
Looks like it's in the preview server resolver:

```

      +/home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:2462:in `block in create': can't modify frozen String (RuntimeError)
      +	from /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:2462:in `scan'
      +	from /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:2462:in `create'
      +	from /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:462:in `each_name'
      +	from /home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/resolv.rb:444:in `getnames'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/dns_resolver/basic_network_resolver.rb:23:in `getnames'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/dns_resolver.rb:48:in `block in names_for'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/dns_resolver.rb:47:in `each'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/dns_resolver.rb:47:in `names_for'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server/information.rb:112:in `resolve_me'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server/server_information.rb:54:in `information'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server/server_information.rb:119:in `bind_address'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server/server_information.rb:71:in `use'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server.rb:182:in `initialize_new_app'
      +	from /home/travis/build/middleman/middleman/middleman-core/lib/middleman-core/preview_server.rb:33:in `start'
      +	from /home/travis/build/middleman/middleman/middleman-cli/lib/middleman-cli/server.rb:86:in `server'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
      +	from /home/travis/build/middleman/middleman/middleman-cli/bin/middleman:23:in `<top (required)>'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/bin/middleman:23:in `load'
      +	from /home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/bin/middleman:23:in `<main>'
```

Thoughts, @maxmeyer?

**Comment by Arcovion** [comment]
String literals are frozen in Ruby 2.3.0 so there's probably a lot of these errors.

**Comment by dg-ratiodata** [comment]
@tdreyno Looking at the stack trace that seems to be a bug in ruby core. I just pass in a string.
@Arcovion Does /usr/lib/ruby/2.3.0/resolv.rb contains that `# frozen_string_literal: true` special string?

**Comment by Arcovion** [comment]
@dg-ratiodata Just checked, it does indeed.

**Comment by dg-ratiodata** [comment]
Damn. Then we need to open a bug report at MRI ruby.

**Comment by dg-ratiodata** [comment]
Filed a bug report at MRI ruby: https://bugs.ruby-lang.org/issues/11910.

**Comment by tdreyno** [comment]
This is the new thing where strings === symbols or some such?

**Comment by dg-ratiodata** [comment]
Should be.

**Comment by tricknotes** [comment]
The other failing test is here:
```
TypeError: no implicit conversion from nil to integer
      +	/home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/socket.rb:1266:in `__recvfrom_nonblock'
      +	/home/travis/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/socket.rb:1266:in `recvfrom_nonblock'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.16.2/lib/celluloid/io/udp_socket.rb:22:in `recvfrom'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/rubydns-1.0.2/lib/rubydns/handler.rb:115:in `handle_connection'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `block in run'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `loop'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/rubydns-1.0.2/lib/rubydns/handler.rb:81:in `run'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
      +	/home/travis/build/middleman/middleman/vendor/bundle/ruby/2.3.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

This is caused by `UDPSocket`'s behavior change for Ruby 2.3.
I think it should be fixed on Celluloid::IO: https://github.com/celluloid/celluloid-io/pull/163
And it may workaround is required to rubydns until version bump of Celluloid::IO: https://github.com/ioquatix/rubydns/pull/56 .

**Comment by dg-ratiodata** [comment]
@tricknotes I think the underlying problem is the same. But the exception shown here has nothing to do with middleman. 

rubydns (gem) != `resolv.rb`  (part of ruby core)

**Pull request merged**
