### PR TITLE
Move partials into partial dir for padrino 0.13.3 compatibility

### PR DESCRIPTION
**Pull request by kjg**

### CODE REVIEW

**Comment by tdreyno** [comment]
Wait, so they changed something about partials in a patch release?

**Comment by kjg** [comment]
I didn't spend too much time trying to figure out exactly which commit
changed the behavior. But moving this partial into the partial directory
seems to make specs pass again.

**Comment by kjg** [comment]
Are you open to merging this?

**Comment by tdreyno** [comment]
I'd like to avoid forcing people to move a bunch of their files. I'd really like to find another solution. But I haven't had enough time to check the latest Padrino changes.

**Comment by kjg** [comment]
Do people not keep their partials in the partials dir? Either way, this PR
doesn't change that. This PR just fixes the current failing specs on the
**master** branch.

The other way we can fix the specs is by pinning padrino to < 0.13.3

Just let me know which way to go, but currently master has failing tests
and we should fix them.

**Comment by kjg** [comment]
I believe this is the change https://github.com/padrino/padrino-framework/pull/2047/files but it ultimately shouldn't matter, **master** does not pass CI right now.

How would you like it fixed, we can pin padrino to < 0.13.3 or we can merge this PR or do something different

**Comment by tdreyno** [comment]
Hmm, so maybe it's a load order thing? We're also overloading their render method to implement partial stuff.

Best case fix would be to support latest Padrino, but also let the current tests pass.

Sorry, but I'm completely slammed at work, so PR reviews are quite slow right now. Thanks for contributing.

**Comment by kjg** [comment]
So it's expected that partials can just be put anywhere for middleman?

**Comment by stevenosloan** [comment]
@kjg that's my understanding at least -- [a little](https://github.com/middleman/middleman/issues/1732) [backstory](https://github.com/middleman/middleman/issues/1963), the partials directory got dropped in v4.

Digging in on that Padrino change, it's pretty subtle -- but if a template *doesn't* have a directory in it's name there will be a '.' prefixed once the template_path gets joined up, which I *think* is throwing off the MM render method.

```
==== testing with path/thing.erb
-> output for old
   path: path
   name: thing.erb
   template_path: path/_thing.erb
-> output for new
   path: path
   name: thing.erb
   template_path: path/_thing.erb
==== testing with thing.erb
-> output for old
   path:
   name: thing.erb
   template_path: /_thing.erb
-> output for new
   path: .
   name: thing.erb
   template_path: ./_thing.erb
```

So in that specific spec, moving the called partials *next* to the files that were asking for them let the relative path lookup in locate_partial (in middleman) find them. I've gotta hop off to some other stuff, but I *think* changing the regex here https://github.com/middleman/middleman/blob/master/middleman-core/lib/middleman-core/template_context.rb#L132 to `/^\.?\//` so that it would also strip a leading '.' should fix things and be compatible w/ older Pandrino?

**Comment by kjg** [comment]
@stevenosloan Yeah there is a couple of different places this could be accounted for in middleman, I was looking at making this change:

```diff
diff --git a/middleman-core/lib/middleman-core/template_context.rb b/middleman-core/lib/middleman-core/template_context.rb
index 5efd8c4..fa451a8 100644
--- a/middleman-core/lib/middleman-core/template_context.rb
+++ b/middleman-core/lib/middleman-core/template_context.rb
@@ -101,7 +101,7 @@ module Middleman
     # @return [String]
     Contract Any, Or[Symbol, String], Hash => String, Maybe[Proc] => String
     def render(_, name, options={}, &block)
-      name = name.to_s
+      name = name.to_s.sub(/^\.\//, '')

       partial_file = locate_partial(name, false) || locate_partial(name, true)
```

but maybe the right thing to do is to fix Padrino instead since this is a breaking change with them

**Comment by stevenosloan** [comment]
Yeah fixing in Padrino seems like the best option to me, doesn't seem like that was an intentional change -- especially w/ one of the use cases being middleman (https://github.com/padrino/padrino-framework/issues/1872) ... and looks like you're already on it 👍

**Comment by tdreyno** [comment]
Thanks for the digging @stevenosloan

**Comment by kjg** [comment]
This has been fixed in padrino 13.3.3.1

**Comment by tdreyno** [comment]
Awesome. Thanks!

**Pull request closed without merging**
