### PR TITLE
Corrected lorem.image

### PR DESCRIPTION
**Pull request by jbpfran**
change supplier for image placeholder to dummyimage.com since placeholder.it doesn't exist any longer.
related to issue [#2540](https://github.com/middleman/middleman/issues/2540)

### CODE REVIEW

**Comment by tdreyno** [comment]
Is this targetting the wrong branch?

**Comment by markets** [comment]
@jbpfran could you please start this branch from https://github.com/middleman/middleman/tree/4.x? 🙏🏼 

In #2575 we have the change for `master` branch (targets v5), but would be nice to have the fix also in v4 branch.

Thanks!

**Comment by jbpfran** [comment]
I opened the PR on both branches.

**Comment by markets** [comment]
> I opened the PR on both branches.

Yes! and this one targets `4.x` branch, but you probably started from `master` and you should start from `4.x`. 

This branch is un-mergeable in its actual state (250 commits, over 400 touched files, ...):

Captura de pantalla 2022-10-10 a las 20 22 26

**Pull request closed without merging**
