### PR TITLE
Refactor frontmatter parsing, closes #1603

### LINKED ISSUE #1603: Bug: Frontmatter documentation page seem to be corrupted
or at least incomplete:
middleman__frontmatter

### PR DESCRIPTION
**Pull request by Arcovion**
Do not merge.
Doesn't work yet, idk why... ¯\\\_(ツ)_/¯
Will wait till the tests are working and then figure out where I went wrong.

### CODE REVIEW

**Comment by tdreyno** [comment]
Pushed fixed test suite, but haven't gotten all the tests passing yet.

**Comment by tdreyno** [comment]
Okay, test suite should be trustworthy now, still fixing a couple tests, but they are low impact

**Comment by Arcovion** [comment]
Ok just needed one extra condition:
```ruby
if frontmatter.nil?
  return [{}, content]
end
```
Rebased and ready to merge as long as the tests pass...

**Comment by Arcovion** [comment]
This should be fine, [one test passed](https://travis-ci.org/middleman/middleman/jobs/81257872) and the rest seem to be unrelated.

**Comment by tdreyno** [comment]
@Arcovion This broke the "Scenario: Using data postscript" test, which is also reliant on frontmatter parsing

**Comment by tdreyno** [comment]
Actually all 3 of these:

```
cucumber features/data.feature:55 # Scenario: Using data postscript
cucumber features/front-matter-neighbor.feature:61 # Scenario: A template should handle an empty YAML feed
cucumber features/front-matter.feature:32 # Scenario: YAML not on first line, no encoding
```

**Comment by Arcovion** [comment]
Thanks, what command do I run to test the individual features instead of the whole test suite?
Last two should be fixed in #1608, wasn't aware of the postscript feature &mdash; that's new in v4 right? Is there a list of all the new features? Too much to keep track of myself =]

**Comment by tdreyno** [comment]
`cd middleman-core && bundle exec cucumber features/data.feature`

et cetera

**Comment by tdreyno** [comment]
Yeah, Postscript is like upside down front matter. Allowing YAML files to have a nice place form long-form text content separate from YAML's indentation rules. Would allow all blog content to move from `.html.erb` to `.yaml`. Needed it for some CMS-heavy projects.

**Comment by Arcovion** [comment]
Huh I just realized JSON frontmatter wasn't even implemented before this PR. It was only in the guides!

**Comment by tdreyno** [comment]
I had removed it from v4 :-p, but only because nobody used it. If it requires no extra code, I guess it can come back :)

**Comment by Arcovion** [comment]
Ahh, yea and I think it's broken too since I forgot to add curly braces, no tests for it.
It's only two lines, should I fix it (just `frontmatter` &rarr; `"{#{frontmatter}}"`) or delete it?

**Comment by tdreyno** [comment]
Yeah. fix it, I'll bring the tests back from v3

**Pull request merged**
