### PR TITLE
Add some requires to help #1601

### PR DESCRIPTION
**Pull request by tommysanterre**
Fix errors for issue #1601

### CODE REVIEW

**Comment by tommysanterre** [comment]
I fixed some error but I still have one

```
== The Middleman is loading
c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:182:in `rescue in create_default_data_source': No source of timezone data could be found. (TZInfo::DataSourceNotFound)
Please refer to http://tzinfo.github.io/datasourcenotfound for help resolving this error.
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:179:in `create_default_data_source'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:40:in `block in get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `synchronize'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/data_source.rb:39:in `get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:629:in `data_source'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:92:in `get'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:67:in `real_timezone'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone_proxy.rb:30:in `period_for_utc'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/tzinfo-1.2.2/lib/tzinfo/timezone.rb:549:in `current_period'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:282:in `utc_offset'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `block in []'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `tap'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/values/time_zone.rb:243:in `[]'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb:61:in `find_zone!'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-blog-3.5.3/lib/middleman-blog/extension.rb:106:in `after_configuration'
        from c:/source/middleman/middleman-core/lib/middleman-core/extension.rb:131:in `block in bind_after_configuration'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/extensions.rb:179:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/data.rb:31:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/application.rb:210:in `initialize'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:56:in `new'
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:56:in `inst'
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:132:in `new_app'
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:33:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli/server.rb:89:in `server'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
        from c:/Ruby21/bin/middleman:23:in `load'
        from c:/Ruby21/bin/middleman:23:in `<main>'
```

**Comment by Arcovion** [comment]
Please post your `Gemfile`, `tzinfo-data` should be included for Windows. I think these requires probably don't fix the root problem, we should get everything working on your machine first.

**Comment by tommysanterre** [comment]
Gemfile
```
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", path: "../middleman" # This is branch v3-stable with my changes
gem "middleman-blog"
gem "middleman-livereload"

# For feed.xml.builder
gem "builder", "~> 3.0"
gem "middleman-deploy"
gem "middleman-disqus"
gem 'middleman-minify-html'
gem "middleman-syntax"
gem "nokogiri"
gem 'middleman-s3_sync'
gem "middleman-google-analytics"
gem "middleman-cloudfront"
gem "dotenv"
```

What do I need to to get the ```tzinfo-data``` ?

**Comment by tommysanterre** [comment]
The tzinfo gem itself seem's to work.

```
$ irb
irb(main):001:0> require 'tzinfo'
=> true
irb(main):002:0> tz = TZInfo::Timezone.get('America/New_York')
=> #<TZInfo::DataTimezone: America/New_York>
irb(main):003:0> local = tz.utc_to_local(Time.utc(2005,8,29,15,35,0))
=> 2005-08-29 11:35:00 UTC
irb(main):004:0> now = tz.now
=> 2015-10-18 00:21:55 UTC
```

**Comment by Arcovion** [comment]
It's an extra gem, just add `tzinfo-data` to your `Gemfile`.
I think you may need to specify `branch: 'v3-stable'` to the `middleman` line else it'll default to master, but I'm not sure.

**Comment by tommysanterre** [comment]
Adding ```gem "tzinfo-data"``` to my gem file fixed that last error. I don't need to specify the branch for middleman as i'm working from my local git repository clone to have my changes for the padrino-helpers errors. Now that it's working I have a different error. middleman-sprockets can't find my favicon which is prensent at the specified path. Which is weird because the same code works under linux. 

```
tommy@FREEZA /c/source/www.tommysanterre.me-middleman (master)                                                              
$ middleman                                                                                                                 
WARN: Unresolved specs during Gem::Specification.reset:                                                                     
      rack (< 2.0, >= 1.0, >= 1.0.0, >= 1.4.5)                                                                              
      hooks (~> 0.3)                                                                                                        
      mime-types (>= 1.16)                                                                                                  
      activesupport (>= 3.1, ~> 4.1)                                                                                        
      rb-fsevent (>= 0.9.3)                                                                                                 
      ffi (>= 0.5.0)                                                                                                        
WARN: Clearing out unresolved specs.                                                                                        
Please report a bug if this causes problems.                                                                                
ansi: 'gem install win32console' to use color on Windows                                                                    
== The Middleman is loading                                                                                                 
c:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:153:in `resolve': couldn't find file 'c:\source\ww
w.tommysanterre.me-middleman\source\images\favicon.ico' (Sprockets::FileNotFound)                                           
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/asset.rb:12:in `initialize
'                                                                                                                           
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:99:in `new'  
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:99:in `block 
in manipulate_resource_list'                                                                                                
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:98:in `each' 
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-sprockets-3.4.2/lib/middleman-sprockets/extension.rb:98:in `manipu
late_resource_list'                                                                                                         
        from c:/source/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:217:in `block (2 levels) in ensure_resou
rce_list_updated!'                                                                                                          
        from c:/source/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:216:in `each'                           
        from c:/source/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:216:in `block in ensure_resource_list_up
dated!'                                                                                                                     
        from c:/Ruby21/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'                                                   
        from c:/source/middleman/middleman-core/lib/middleman-core/sitemap/store.rb:208:in `ensure_resource_list_updated!'  
        from c:/source/middleman/middleman-core/lib/middleman-core/sitemap/extensions/on_disk.rb:31:in `block in initialize'
                                                                                                                            
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'                       
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'                               
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'                        
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'                                
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'                     
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'                      
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'                          
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'                                  
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'                                
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'                                   
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'                               
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'                     
        from c:/source/middleman/middleman-core/lib/middleman-core/core_extensions/request.rb:57:in `inst'                  
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:132:in `new_app'                       
        from c:/source/middleman/middleman-core/lib/middleman-core/preview_server.rb:33:in `start'                          
        from c:/source/middleman/middleman-core/lib/middleman-core/cli/server.rb:89:in `server'                             
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'                                 
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'                  
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'                                   
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'                                 
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:72:in `method_missing'                            
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'                                 
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'                                
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'                  
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'                                   
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'                                 
        from c:/source/middleman/middleman-core/lib/middleman-core/cli.rb:20:in `start'                                     
        from c:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'                 
        from c:/Ruby21/bin/middleman:23:in `load'                                                                           
        from c:/Ruby21/bin/middleman:23:in `<main>'                                                                         
```

**Comment by tommysanterre** [comment]
Also I think that tzinfo-data shouldn't be in my Gemfile but in the one of whichever gem actually requires it.

**Comment by tdreyno** [comment]
@tommysanterre `tzinfo-data` is in the default Middleman Gemfile. Is there a template somewhere not including it by default?

**Comment by tommysanterre** [comment]
@tdreyno you're right I just created a new project and it's included by default. Maybe I removed it or it was not included in a previous version.

**Comment by tommysanterre** [comment]
I still have the sprocket error. Any ideas on that?

**Comment by tdreyno** [comment]
Sprockets often falls down when dealing with special characters in file paths. Can you try moving the project out of the `www` folder you have?

**Comment by tommysanterre** [comment]
Still have the same issue

== The Middleman is loading
c:/Ruby21/lib/ruby/gems/2.1.0/gems/sprockets-2.12.4/lib/sprockets/base.rb:153:in `resolve': couldn't find file 'c:\source\simplePath\source\images\favicon.ico' (Sprockets::FileNotFound)

**Comment by tommysanterre** [comment]
And just to prove that the file really is there

```
c:\source\simplePath>ls c:\source\simplePath\source\images\favicon.ico
c:\source\simplePath\source\images\favicon.ico
``

**Comment by tdreyno** [comment]
Hmm, I'd suggest moving it out of images into source for now, but that's definitely some kind of bug.

**Comment by tdreyno** [comment]
It may be that Sprockets doesn't understand the file type... not sure

**Comment by tommysanterre** [comment]
Hum, moving it to source worked but now the next file in the image folder which is a .jpeg is not being found.

**Comment by tommysanterre** [comment]
I will keep looking into that last issue, thanks for merging my pull request @tdreyno .

**Comment by tdreyno** [comment]
Thanks for researching and submitting!

**Comment by vizcay** [comment]
I'm having the exac same issue #1601 on one of my employees windows box. But I'm running middleman 4.2.1.

This pull request cannot be merged on 4.x as well? I mean, it looks like a general thing when on windows, nothing specific to v3.x.

```
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions/default_helpers.rb:8:in `<top (required)>': uninitialized constant Padrino::Helpers::OutputHelpers (NameError)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions.rb:45:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/core_extensions.rb:45:in `block in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:91:in `load'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:127:in `block in load_settings'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:125:in `each'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/extensions.rb:125:in `load_settings'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/extension_manager.rb:12:in `initialize'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:263:in `new'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.1/lib/middleman-core/application.rb:263:in `initialize'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `new'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.1/bin/middleman:49:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/bin/middleman:23:in `load'
        from C:/RailsInstaller/Ruby2.3.3/bin/middleman:23:in `<main>
```

**Pull request merged**
