### PR TITLE
Fix i18n with anchor v4

### LINKED ISSUE #2286: Using the `:anchor` argument with i18n's url_for function is broken
## Expected behavior and actual behavior

When calling `url_for` with `i18n` enabled and using the `:anchor` argument, the link that is generated is wrong. Here's an example call:

```ruby
url_for '/index.nl.html', :anchor => 'test'
```
generates: 

```
/index.nl.html#test
```

Whereas it should generate:

```
/nl/index/#test
```

## Steps to reproduce the problem (from a clean middleman installation)

In your config file, enable `i18n`. Make an `/index.nl.html` file. Call the above function

## Additional information

- Ruby version: `ruby 2.5.1p57`
- Middleman version: `4.3.4`
- OS version: Ubuntu 18.04.2

### PR DESCRIPTION
**Pull request by mrtndwrd**
fixes #2286 

I can only test on my website with v4, which is why the target branch is '4.x'.

### CODE REVIEW

**Comment by tdreyno** [comment]
Thank you for these PRs. Could you add a test case where I can see which issue this resolves?

**Comment by mrtndwrd** [comment]
Sure. 

I changed the `i18n_link_to.feature`, which in the 4.x brach fails as follows: 

```
== Locales: en, es (Default en)
    Given the Server is running at "empty-app"                            # lib/middleman-core/step_definitions/server_steps.rb:65
    When I go to "/hello.html"                                            # lib/middleman-core/step_definitions/server_steps.rb:74
    Then I should see "Page: Hello"                                       # lib/middleman-core/step_definitions/server_steps.rb:90
    Then I should see 'Current: /hello.html'                              # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Other: /es/hola.html'                              # lib/middleman-core/step_definitions/server_steps.rb:94
    When I go to "/es/hola.html"                                          # lib/middleman-core/step_definitions/server_steps.rb:74
    Then I should see "Page: Hola"                                        # lib/middleman-core/step_definitions/server_steps.rb:90
    Then I should see 'Current: /es/hola.html'                            # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Other: /hello.html'                                # lib/middleman-core/step_definitions/server_steps.rb:94
    When I go to "/article.html"                                          # lib/middleman-core/step_definitions/server_steps.rb:74
    Then I should see "Page Lang: Default"                                # lib/middleman-core/step_definitions/server_steps.rb:90
    Then I should see 'Current: /article.html'                            # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Other: /es/article.html'                           # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Current with anchor: /article.html#test-anchor'    # lib/middleman-core/step_definitions/server_steps.rb:94
    When I go to "/es/article.html"                                       # lib/middleman-core/step_definitions/server_steps.rb:74
    Then I should see "Page Lang: Spanish"                                # lib/middleman-core/step_definitions/server_steps.rb:90
    Then I should see 'Current: /es/article.html'                         # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Other: /article.html'                              # lib/middleman-core/step_definitions/server_steps.rb:94
    Then I should see 'Current with anchor: /es/article.html#test-anchor' # lib/middleman-core/step_definitions/server_steps.rb:94
      expected "Page Lang: Spanish\n\nCurrent: /es/article.html\nOther: /article.html\nCurrent with anchor: /article.html#test-anchor" to include "Current with anchor: /es/article.html#test-anchor"
      Diff:
      @@ -1,2 +1,6 @@
      -Current with anchor: /es/article.html#test-anchor
      +Page Lang: Spanish
      +
      +Current: /es/article.html
      +Other: /article.html
      +Current with anchor: /article.html#test-anchor
       (RSpec::Expectations::ExpectationNotMetError)
      ./lib/middleman-core/step_definitions/server_steps.rb:95:in `/^I should see '([^]*)'$/'
      features/i18n_link_to.feature:213:in `Then I should see 'Current with anchor: /es/article.html#test-anchor''
```

And I added a scenario to the Markdown (Kramdown) feature, which fails as follows in 4.x:

```
  Scenario: Kramdown uses our link_to with options parameter # features/markdown_kramdown.feature:40
    Given a fixture app "markdown-app"                       # lib/middleman-core/step_definitions/middleman_steps.rb:16
    And a file named "config.rb" with:                       # aruba-0.7.4/lib/aruba/cucumber.rb:34
      """
      set :markdown_engine, :kramdown
      activate :directory_indexes
      """
    And a file named "source/links.html.markdown" with:      # aruba-0.7.4/lib/aruba/cucumber.rb:34
      """
      [A link](/smarty_pants.html)
      [A second link](/smarty_pants.html){: anchor="test-anchor"}
      """
    Given the Server is running at "markdown-app"            # lib/middleman-core/step_definitions/server_steps.rb:65
    When I go to "/links/"                                   # lib/middleman-core/step_definitions/server_steps.rb:74
    Then I should see "/smarty_pants/"                       # lib/middleman-core/step_definitions/server_steps.rb:90
    And I should see "/smarty_pants/#test-anchor"            # lib/middleman-core/step_definitions/server_steps.rb:90
      expected "<p><a href=\"/smarty_pants/\">A link</a>\n<a href=\"/smarty_pants/\" anchor=\"test-anchor\">A second link</a></p>\n" to include "/smarty_pants/#test-anchor"
      Diff:
      @@ -1,2 +1,3 @@
      -/smarty_pants/#test-anchor
      +<p><a href="/smarty_pants/">A link</a>
      +<a href="/smarty_pants/" anchor="test-anchor">A second link</a></p>
       (RSpec::Expectations::ExpectationNotMetError)
      ./lib/middleman-core/step_definitions/server_steps.rb:91:in `/^I should see "([^\"]*)"$/'
      features/markdown_kramdown.feature:55:in `And I should see "/smarty_pants/#test-anchor"'

```

Both succeed in this PR.

**Comment by tdreyno** [comment]
:+1:

**Comment by tdreyno** [comment]
Published as v4.3.5

**Pull request merged**
