### PR TITLE
Backport of i18n lookup table changes to 4.x, fixes misc url_for issues

### LINKED ISSUE #2280: url_for produces the wrong link in some cases with localized pages
## Expected behavior and actual behavior

`url_for` produces the wrong link in some cases when used from localized pages.

Apparently this happens when the following conditions are met:
 * `url_for` is being used from a localized URL for a language that is *not* mapped at root
 * The page name passed to `url_for` includes the page extension (e.g. `products.html`)

## Steps to reproduce the problem (from a clean middleman installation)

Here's a test repo: https://github.com/guillerodriguez/middleman-url_for-test

If you browse the index.html page in this repo, the results are as follows: 

- URL for index.html,en: /
- URL for index.html,fr: /fr/
- URL for index.html,es: /es/
- URL for test.html,en: /test.html
- URL for test.html,fr: /fr/test.html
- URL for test.html,es: /es/test.html
- URL for index,en: /
- URL for index,fr: /fr/
- URL for index,es: /es/
- URL for test,en: /test.html
- URL for test,fr: /fr/test.html
- URL for test,es: /es/test.html

These are all OK. However if you browse /es/index.html, the results are as follows:

- URL for index.html,en: /es/
- URL for index.html,fr: /es/
- URL for index.html,es: /es/
- URL for test.html,en: /es/test.html
- URL for test.html,fr: /es/test.html
- URL for test.html,es: /es/test.html
- URL for index,en: /
- URL for index,fr: /fr/
- URL for index,es: /es/
- URL for test,en: /test.html
- URL for test,fr: /fr/test.html
- URL for test,es: /es/test.html

In this case, the first 6 results are wrong.

## Additional information

- Ruby version: 2.3.8p459
- Middleman version: 4.3.4
- OS version: Ubuntu 14

### LINKED ISSUE #2592: Helper url_for doesn't generate correct i18n URL for entirely localized templates
## Expected behavior and actual behavior

With a Middleman config with i18n plugin activated as follows:

```rb
activate :i18n, :langs => [:en, :es], :mount_at_root => false
```
I have set up two localized pages, one of them uses [fully localized template](https://middlemanapp.com/advanced/localization/#localizing-entire-templates), the other doesn't:

- `source/localizable/path1.html.erb`
- `source/localizable/path2.en.html.erb`
- `source/localizable/path2.es.html.erb`

I want to get the reference to those pages using `url_for` helper from other pages, so I wrote this `source/localizable/index.html.erb`:

```erb
<h3><%= t(:home) %></h3>

<a href="<%= url_for '/path1.html' %>">Working path</a><br>
<a href="<%= url_for '/path2.html' %>">Wrong path</a>
```

However, the output of `/en/index.html` after building it is:

```html
<h3>Home</h3>

<a href="/en/path1.html">Working path</a><br> # Correct
<a href="/path2.html">Wrong path</a> # Should be /en/path2.html
```

As you can see, it is returning the correct reference to `path1.html`, but shows `/path2.html` for the second link instead of `/en/path2.html` as it should be.

In addition, if I change "path2" template filename from `path2.en.html.erb` to `path2.html.erb`, it generates the correct reference, i.e., "/en/path2.html"

## Steps to reproduce the problem (from a clean middleman installation)

I have uploaded this [test repository](https://github.com/phvega/url_for-test)

## Additional information

- Ruby version: ruby 2.6.8p205 (2021-07-07 revision 67951) [x86_64-linux]
- Middleman version: 4.4.3
- OS version: Ubuntu 20.04.1

### PR DESCRIPTION
**Pull request by guillerodriguez**
Backport of #2263 (reimplementation of i18n lookup table) to 4.x branch, including a fix for issue #2594, which was introduced by the referenced PR.

Fixes #2280, fixes #2592.

### CODE REVIEW

**Comment by markets** [comment]
Thanks for that @guillerodriguez! The current situation of MM (`v4` vs `v5`) is a bit weird and confusing for contributors 🙏🏼 

Last month I've discussed with @tdreyno and we came up with this plan: https://github.com/middleman/middleman/issues/2569#issuecomment-1310796229.

**Comment by guillerodriguez** [comment]
> Thanks for that @guillerodriguez! The current situation of MM (`v4` vs `v5`) is a bit weird and confusing for contributors 🙏🏼
> 
> Last month I've discussed with @tdreyno and we came up with this plan: [#2569 (comment)](https://github.com/middleman/middleman/issues/2569#issuecomment-1310796229).

If this helps making MM move forward then it is welcome :-)

**Comment by tdreyno** [comment]
@guillerodriguez I can merge if you're able to resolve those broken tests

**Comment by guillerodriguez** [comment]
> @guillerodriguez I can merge if you're able to resolve those broken tests

@tdreyno Not sure these failures are actually related to the changes in the PR -- all jobs failed early, in the ruby/setup-ruby@v1 action. This is before actually attempting to run any tests...

**Comment by tdreyno** [comment]
Can you re-run the tests, might have been a GH issue. I don't have permissions to restart your actions

**Comment by guillerodriguez** [comment]
> Can you re-run the tests, might have been a GH issue. I don't have permissions to restart your actions

I don't think I can do that either (or can't find how), perhaps because it's been [more than 30 days since the original run](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs). I will try to update the branch to see if that triggers a re-run.

**Comment by guillerodriguez** [comment]
> > Can you re-run the tests, might have been a GH issue. I don't have permissions to restart your actions
> 
> I don't think I can do that either (or can't find how), perhaps because it's been [more than 30 days since the original run](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs). I will try to update the branch to see if that triggers a re-run.

Anyway the above link says:

**Who can use this feature**
People with write permissions to a repository can re-run workflows in the repository.

doesn't seem to 

> > Can you re-run the tests, might have been a GH issue. I don't have permissions to restart your actions
> 
> I don't think I can do that either (or can't find how), perhaps because it's been [more than 30 days since the original run](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs). I will try to update the branch to see if that triggers a re-run.

Done. Now it says the workflow is "awaiting approval from a maintainer": https://github.com/middleman/middleman/actions/runs/4106777042

**Comment by guillerodriguez** [comment]
> > > Can you re-run the tests, might have been a GH issue. I don't have permissions to restart your actions
> > 
> > 
> > I don't think I can do that either (or can't find how), perhaps because it's been [more than 30 days since the original run](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#about-re-running-workflows-and-jobs). I will try to update the branch to see if that triggers a re-run.
> 
> Done. Now it says the workflow is "awaiting approval from a maintainer": https://github.com/middleman/middleman/actions/runs/4106777042

Success :-)

**Comment by tdreyno** [comment]
Thank you 🙏🏻 @guillerodriguez

**Pull request merged**
