### PR TITLE
Add "before_server"-hook to preview server in v3

### PR DESCRIPTION
**Pull request by maxmeyer**
This is a backport of the changes in v4 to make the server hook available in v3 as well.

@tdreyno I use v3 for some production environments. I hope to find some time to replace some ruby scripts with an extension using the new hook.

### CODE REVIEW

**Comment by tdreyno** [comment]
@maxmeyer I owe you so many :beers:

**Comment by maxmeyer** [comment]
No problem. :-) You're welcome.

**Comment by dlitvakb** [comment]
@maxmeyer :heart:

**Comment by dlitvakb** [comment]
@maxmeyer @tdreyno any notice on when this will be released?

**Comment by tdreyno** [comment]
Good question. Could do a stable release this week

**Comment by tdreyno** [comment]
Done. v3.4.1

**Pull request merged**
