### PR TITLE
Remove Asciidoc support in favor of a middleman-asciidoc extension

### PR DESCRIPTION
**Pull request by bhollis**
I've moved and partially rewritten our Asciidoc support into a separate extension, and I've given @mojavelinux admin access to it. This PR removes the Asciidoc support from core for v4 in favor of that extension.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Is it possible to tell middleman to ignore certain files that are needed in the template source repository but not in the generated project?

**Comment by Arcovion** [comment]
Prefix them with an underscore or use the ignore method in `config.rb`:
```ruby
ignore 'this.html'
```

**Comment by mojavelinux** [comment]
I can't prefix with an underscore or else the file won't serve it's purpose
in the template project. I'll try the ignore, but I suspect that's going to
carry over and ignore the file once it's part of the project.

I'll file a separate issue to discuss in more detail.

**Comment by tdreyno** [comment]
Sounds like a different issue, thanks @mojavelinux

**Comment by mojavelinux** [comment]
Filed as https://github.com/middleman/middleman/issues/1419.

**Pull request merged**
