### PR TITLE
Remove Compass

### PR DESCRIPTION
**Pull request by tysongach**
This is a WIP, as I don’t really know what I’m doing here.

[Compass] is no longer actively maintained, so we should remove it from Middleman.

[Compass]: https://github.com/Compass/compass

### CODE REVIEW

**Comment by tdreyno** [comment]
Sounds smart to me.

**Comment by tdreyno** [comment]
That said, it's already in an extension so we can keep it for legacy

**Comment by tysongach** [comment]
@tdreyno I’m not sure I’m following. Is the extension fully agnostic and these changes are fine (most are descriptions/mentions of Compass)?

My only hesitation was the changes to the `Gemfile` and `middleman/middleman.gemspec` ( the dependency for `compass-import-once`).

What prompted this issue initially was me being prompted about Compass when doing a `middleman init`. I just realized this is actually coming from the default template: https://github.com/middleman/middleman-templates-default/blob/master/Thorfile#L13-L15

Thoughts on removing that prompt?

**Comment by tysongach** [comment]
I put up a PR to remove the Compass prompt: https://github.com/middleman/middleman-templates-default/pull/9

**Comment by tysongach** [comment]
@tdreyno With the removal of the Compass prompt in the `middleman-templates-default`, I think these changes are still valid, yeah? The changes here seem to be leftover from legacy built-in Compass. People should still be able to use the extension if needed.

**Pull request merged**
