### PR TITLE
discover template in local directory if applicable

### PR DESCRIPTION
**Pull request by mojavelinux**
- look for template in local directory
- use looser check for SSH git URL

### CODE REVIEW

**Comment by mojavelinux** [comment]
I wonder if we should require that the local directory be an absolute path (using Pathname(repo_name).absolute?). That might make it less likely to accidentally find a matching local path. wdyt?

I also split out the clone operation to a dedicated function.

**Comment by tdreyno** [comment]
@mojavelinux I think it's a good idea to make it absolute and error loudly in case of conflict.

**Comment by mojavelinux** [comment]
In that case, let's do it!

**Comment by mojavelinux** [comment]
I'll rebase.

**Comment by mojavelinux** [comment]
Rebase complete!

**Pull request merged**
