### PR TITLE
Update thor from 0.19.4 to 1.2.1 on test

### PR DESCRIPTION
**Pull request by tnir**
To remove the following warnings in Ruby 3.1, updates `thor` gem to the latest:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
```

thor 1.2.0 fixed in https://github.com/rails/thor/pull/761.

thor 1.2.1 <https://rubygems.org/gems/thor/versions/1.2.1> still supports for Ruby 2.0 or higher, which meets the required Ruby version (2.5+) of this gem.

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by tnir** [comment]
`CI / ubuntu-ruby-3 (pull_request)` job fails only due to #2557. Once it is merged, I will update this change.

**Review by markets — APPROVED** [review]

**Comment by tnir** [comment]
@markets Could you update the branch protection rule first instead of approval?

**Comment by markets** [comment]
sorry I can't! I don't have permissions on this repository, just trying to help reviewing pull requests.

**Comment by tnir** [comment]
Thanks. Let us move on #2558 to wait @tdreyno for feedback then!

**Pull request merged**
