### PR TITLE
[branch 4.x] Minify JS: migrate from Uglifier to Terser gem to support ES6

### LINKED ISSUE #2530: Migrate from Uglifier to Terser
ℹ️ _This is more a feature request than an issue_

---

Hi @tdreyno and Middleman community 👋🏼 

First of all thank you so much for maintaining such an incredible project, still the best SSG IMO 🤘🏼

Even the External Pipeline is awesome and I love it (just created a cool template: https://github.com/ralixjs/middleman-ralix-tailwind) for new projects, I still have other MM sites with the following setup:
 
**MM v4 + Sprockets + Bootstrap v5 gem**

Which is quite easy to get it up, without the need of a js bundler. But that setup is actually crashing when using the `:minify_javascript` setting, as Uglifier doesn't support ES6 syntax (coming from Bootstrap gem):

```
error  build/javascripts/application-ec337532.js
SyntaxError: Unexpected token: expand (...)
JS_Parse_Error.get ((execjs):3538:621)
(execjs):4077:53
(execjs):1:40
Object.<anonymous> ((execjs):1:58)
Module._compile (node:internal/modules/cjs/loader:1101:14)
Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
Module.load (node:internal/modules/cjs/loader:981:32)
Function.Module._load (node:internal/modules/cjs/loader:822:12)
Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
node:internal/main/run_main_module:17:47
/Users/markets/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec'
...
```

To fix it, I made the following changes:

```diff
diff --git a/Gemfile b/Gemfile
index afc9a85..15a2529 100755
--- a/Gemfile
+++ b/Gemfile
@@ -4,6 +4,7 @@ gem "middleman", "~> 4.4"
 gem "middleman-livereload" , "~> 3.4"
 gem "middleman-sprockets", "~> 4.0.0"
 gem "bootstrap", "~> 5.1.0"
+gem "terser", "~> 1.1"
 
 group :development do
   gem "byebug"
diff --git a/Gemfile.lock b/Gemfile.lock
index c23ce8a..0dde00c 100755
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -163,6 +163,8 @@ GEM
       activesupport (>= 5.2)
       sprockets (>= 3.0.0)
     temple (0.8.2)
+    terser (1.1.8)
+      execjs (>= 0.3.0, < 3)
     thor (1.2.1)
     tilt (2.0.10)
     toml (0.3.0)
@@ -184,6 +186,7 @@ DEPENDENCIES
   middleman (~> 4.4)
   middleman-livereload (~> 3.4)
   middleman-sprockets (~> 4.0.0)
+  terser (~> 1.1)
 
 BUNDLED WITH
    2.2.17
diff --git a/config.rb b/config.rb
index 8beefed..2a7c1b2 100755
--- a/config.rb
+++ b/config.rb
@@ -1,3 +1,5 @@
+require 'terser'
+
 set :title, "Bajo Aragón Club de Vehículos Antiguos"
 set :email, "bajoaragonclub@hotmail.com"
 set :facebook, "bajoaragonclub"
@@ -11,7 +13,9 @@ end
 
 configure :build do
   activate :minify_css
-  activate :minify_javascript
+  activate :minify_javascript, compressor: Terser.new
   activate :asset_hash
   activate :relative_assets
 end
```

In the Uglifier docs you can read (https://github.com/lautis/uglifier#uglifier):

> UglifyJS only works with ES5. If you need to compress ES6, ruby-terser is a better option.

So maybe it makes sense to fix it in MM itself? I mean, moving from Uglifier to Terser. 

**EXTRA INFO** Rails also switched the default to Terser: https://github.com/rails/rails/pull/42622

Best,
Marc

### PR DESCRIPTION
**Pull request by markets**
ℹ️ **The branch targets v4 branch**

Ref: #2530

### CODE REVIEW

**Comment by markets** [comment]
Hello @tdreyno! Pretty sure the CI errors are unrelated to this change. Let me know if I can do something to help move this forward. Thank you so much!

**Comment by tdreyno** [comment]
The Ruby 3 seems like it could be something else, but the rest are definitely failing the minify_js test suite.

**Comment by markets** [comment]
Ah yes! It seems the first CI run (under 3.0) was canceled. Just took a look at the error and it seems related to the default options in Terser for "IIFE". So maybe these changes in specs are acceptable 🤔 ?

There are also a couple of configuration options for the constructor, but I played a bit with them with no luck matching the current output:

```diff
   option :compressor, proc {
     require 'terser'
-    ::Terser.new
+    ::Terser.new(output: { wrap_iife: true }, compress: { negate_iife: false })
   }, 'Set the JS compressor to use.'
```

**Comment by markets** [comment]
Thanks for merging @tdreyno 👍🏼 👍🏼 👍🏼

**Pull request merged**
