### PR TITLE
allow to override data in context

### PR DESCRIPTION
**Pull request by andrezimpel**
Currently the build fails when liquid tries to override the (empty or not existing?) context value data.

cc: https://github.com/middleman/middleman/issues/2083

### CODE REVIEW

**Comment by tdreyno** [comment]
So will this allow Liquid to overwrite Middleman's `data` provider? Or just allow Liquid templates to access it?

**Comment by andrezimpel** [comment]
It will allow Liquid to override the empty data context while rendering. 

`Template local 'data' tried to overwrite an existing context value. Please rename the key when passing to 'locals'` the context value has been empty or is not even existing in mutplile scenarios I have.

**Comment by tdreyno** [comment]
@andrezimpel Do you have YAML files in the `data` folder? If not, can you test with that?

**Comment by andrezimpel** [comment]
I did also test that and everything works fine. What's the intention of context data anyways?

**Pull request merged**
